// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OneLearn.Infrastructure.Common.DBContexts;

#nullable disable

namespace OneLearn.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241216131145_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OneLearn.Domain.Test.Test", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("a")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("b")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("created_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("d")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("e")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("f")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("g")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("h")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("i")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("j")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("k")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("l")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("last_modified_by")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("last_modified_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("m")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("n")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("OneLearn.Domain.Transactions.VoiceTranslation.Language", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("created_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("language")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("language_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("last_modified_by")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("last_modified_on")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("language", "language_Code")
                        .IsUnique();

                    b.ToTable("Language");
                });

            modelBuilder.Entity("OneLearn.Domain.Transactions.VoiceTranslation.Passage", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("created_on")
                        .HasColumnType("datetime2");

                    b.Property<int>("langauge_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("last_modified_by")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("last_modified_on")
                        .HasColumnType("datetime2");

                    b.Property<string>("passage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Passages");
                });
#pragma warning restore 612, 618
        }
    }
}
